apiVersion: v1
kind: Service

metadata: 
  name: yandex-service
  namespace: fleettracker

spec:
  type: ClusterIP

  selector:
    app: yandex

  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081