apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fleettracker

type: Opaque

stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "fleettracker"
  DB_HOST: "postgres-service"
  SECRET_KEY: "dev-secret-key"
  JWT_SECRET_KEY: "jwt-dev-secret"