name: Build containers
on:
  push:
    branches:
      - test
    paths:
      - "application/**"

jobs:
  Build_containers:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build images
        run: docker compose -f compose/docker-compose.yml build